# Generated by Django 4.0.2 on 2022-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
